// Generated by delombok at Sun Nov 21 11:47:36 UTC 2021
/*
 * This file is part of WebGoat, an Open Web Application Security Project utility. For details, please see http://www.owasp.org/
 *
 * Copyright (c) 2002 - 2019 Bruce Mayhew
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; if
 * not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * Getting Source ==============
 *
 * Source for this application is maintained at https://github.com/WebGoat/WebGoat, a repository for free software projects.
 */
package org.owasp.webgoat.csrf;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author nbaars
 * @since 4/8/17.
 */
@XmlRootElement
public class Review {
    private String user;
    private String dateTime;
    private String text;
    private Integer stars;

    @java.lang.SuppressWarnings("all")
    public String getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public String getDateTime() {
        return this.dateTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getText() {
        return this.text;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStars() {
        return this.stars;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final String user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setDateTime(final String dateTime) {
        this.dateTime = dateTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setText(final String text) {
        this.text = text;
    }

    @java.lang.SuppressWarnings("all")
    public void setStars(final Integer stars) {
        this.stars = stars;
    }

    @java.lang.SuppressWarnings("all")
    public Review(final String user, final String dateTime, final String text, final Integer stars) {
        this.user = user;
        this.dateTime = dateTime;
        this.text = text;
        this.stars = stars;
    }

    @java.lang.SuppressWarnings("all")
    public Review() {
    }
}
