// Generated by delombok at Sun Nov 21 11:47:22 UTC 2021
package org.owasp.webgoat.xss;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author nbaars
 * @since 4/8/17.
 */
@XmlRootElement
public class Comment {
    private String user;
    private String dateTime;
    private String text;

    @java.lang.SuppressWarnings("all")
    public String getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public String getDateTime() {
        return this.dateTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getText() {
        return this.text;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final String user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setDateTime(final String dateTime) {
        this.dateTime = dateTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setText(final String text) {
        this.text = text;
    }

    @java.lang.SuppressWarnings("all")
    public Comment(final String user, final String dateTime, final String text) {
        this.user = user;
        this.dateTime = dateTime;
        this.text = text;
    }

    @java.lang.SuppressWarnings("all")
    public Comment() {
    }
}
